# Generated by Django 5.1 on 2024-09-11 06:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Blog Title')),
                ('author', models.CharField(max_length=255, verbose_name='Blog Author')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Blog Content')),
                ('slug', models.SlugField(blank=True, default='slug will generate auto', max_length=255, unique=True, verbose_name='Blog Slug')),
                ('image', models.ImageField(upload_to='images/blog/posts', verbose_name='Blog Image')),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', help_text='Select the status of the blog post', max_length=8)),
                ('conclusion', models.TextField(blank=True, null=True, verbose_name='Blog Conclusion')),
            ],
            options={
                'verbose_name_plural': 'Blog',
                'ordering': ['-id'],
            },
        ),
    ]
