# Generated by Django 5.1 on 2024-09-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogs_options_alter_blogs_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='posted_at',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Blog Slug'),
        ),
    ]
