# Generated by Django 5.1 on 2024-09-11 06:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='service/images/')),
                ('image_2', models.ImageField(upload_to='service/images/')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Ava Content')),
            ],
            options={
                'verbose_name_plural': 'Ava Content',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service/images/', verbose_name='Service Image')),
                ('title', models.CharField(max_length=255, verbose_name='Service Name')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Service Slug')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Service Description')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
    ]
