# Generated by Django 5.1 on 2024-09-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_feedbackform_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyhighlight',
            name='number',
            field=models.CharField(max_length=255, verbose_name='company highlight dummynumber'),
        ),
    ]
