# Generated by Django 5.1 on 2024-09-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_companyhighlight_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackform',
            name='subject',
            field=models.CharField(default='subject required', help_text='Subject of the feedback', max_length=255, verbose_name='Subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyhighlight',
            name='number',
            field=models.CharField(max_length=255, verbose_name='company highlight title'),
        ),
    ]
